name: endguard
version: 0.1.0
description: >-
  Dart implementation of the endguard encryption
homepage: https://github.com/robojones/endguard
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.10
dependencies:
  cryptography: ^2.0.2
  protobuf: ^2.0.0
